# Generated by Django 4.1.7 on 2023-03-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_likes_postlist_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlist',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_ok', to='posts.likes'),
        ),
    ]
