# Generated by Django 4.1.7 on 2023-03-31 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_remove_postlist_reply_postlist_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlist',
            name='likes',
        ),
        migrations.AddField(
            model_name='postlist',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
