# Generated by Django 4.1.7 on 2023-04-01 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_remove_postlist_likes_postlist_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_ok', to='posts.postlist'),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='postcomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
