# Generated by Django 4.1.7 on 2023-04-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postlist_reply_alter_postlist_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
