# Generated by Django 4.1.7 on 2023-03-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmark',
            options={'ordering': ['name'], 'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
    ]
