# Generated by Django 4.1.7 on 2023-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='district_region',
            field=models.CharField(max_length=50, null=True, verbose_name='Район субъекта'),
        ),
    ]
