# Generated by Django 4.1.7 on 2023-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0002_alter_adv_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='district_region',
            field=models.CharField(default='', max_length=50, verbose_name='Район субъекта'),
        ),
    ]
