# Generated by Django 4.1.7 on 2023-03-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0002_alter_carmark_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adv',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='slug',
        ),
    ]
