# Generated by Django 4.1.7 on 2023-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0003_alter_rubric_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=45, verbose_name='Название'),
        ),
    ]
