# Generated by Django 4.1.7 on 2023-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0003_alter_adv_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='district_city',
            field=models.CharField(default='', max_length=50, verbose_name='Район города'),
        ),
    ]
