# Generated by Django 4.1.7 on 2023-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0004_alter_adv_district_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
    ]
