# Generated by Django 4.1.7 on 2023-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0005_alter_adv_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='district_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район города'),
        ),
    ]
