# Generated by Django 4.1.7 on 2023-03-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0005_alter_adv_district_city_alter_adv_district_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Улица'),
        ),
    ]
