# Generated by Django 4.1.7 on 2023-03-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0005_transaction_adv_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='all_adv.transaction', verbose_name='Вид сделки'),
        ),
    ]
