# Generated by Django 4.1.7 on 2023-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0006_alter_adv_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='street',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Улица'),
        ),
    ]
