# Generated by Django 4.1.7 on 2023-03-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0006_alter_adv_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=45, verbose_name='Подрубрика')),
            ],
            options={
                'verbose_name': 'Подрубрика',
                'verbose_name_plural': 'Подрубрики',
            },
        ),
        migrations.AddField(
            model_name='adv',
            name='sub_rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='all_adv.subrubric', verbose_name='Подрубрика'),
        ),
    ]
