# Generated by Django 4.1.7 on 2023-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0007_alter_adv_subrubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='title',
            field=models.CharField(help_text='Это хелп', max_length=50, verbose_name='Заголовок'),
        ),
    ]
