# Generated by Django 4.1.7 on 2023-03-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0007_subrubric_adv_sub_rubric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubRubric',
            new_name='SubRubricTransport',
        ),
        migrations.RenameField(
            model_name='adv',
            old_name='sub_rubric',
            new_name='sub_rubric_transport',
        ),
    ]
