# Generated by Django 4.1.7 on 2023-03-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0008_remove_adv_district_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменено  от'),
        ),
    ]
