# Generated by Django 4.1.7 on 2023-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0008_alter_adv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='car_color',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='car_engine_capacity',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='car_model',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='car_run',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='car_year',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='content',
            field=models.TextField(db_index=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='intention_age',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Возраст поиска'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='adv',
            name='mode',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='price',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='rooms',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Комнат'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='salary',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Зарплата от'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='square_land',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь земли'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='square_rooms',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь комнат'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='street',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='subrubric',
            field=models.CharField(blank=True, choices=[(None, ''), ('Транспортные средства', (('Автомобили', 'Автомобили'), ('Автомобильные запчасти', 'Автомобильные запчасти'), ('Водный транспорт и запчасти', 'Водный транспорт и запчасти'), ('Прицепы и дома', 'Прицепы и дома'), ('Мотоциклы, малая техника и запчасти', 'Мотоциклы, малая техника и запчасти'), ('Воздушные транспортные средства и запчасти', 'Воздушные транспортные средства и запчасти'), ('Другие транспортные средства', 'Другие транспортные средства'))), ('Электроника', (('Компьютеры и комплектующие', 'Компьютеры и комплектующие'), ('Оргтехника', 'Оргтехника'), ('Фото и видео', 'Фото и видео'), ('Телефоны и планшеты', 'Телефоны и планшеты'), ('Телевизоры и ТВ-приставки', 'Телевизоры и ТВ-приставки'), ('Другая электроника', 'Другая электроника'))), ('Недвижимость', (('Квартиры', 'Квартиры'), ('Дома', 'Дома'), ('Комнаты', 'Комнаты'), ('Участки', 'Участки'), ('Коммерческая', 'Коммерческая'))), ('Хозяйство', (('Искусство и антиквариат', 'Искусство и антиквариат'), ('Детские товары и игрушки', 'Детские товары и игрушкит'), ('Одежда', 'Одежда'), ('Сад и огород', 'Сад и огород'), ('Инструмент', 'Инструмент'), ('Мебель', 'Мебель'), ('Домашний декор', 'Домашний декор'), ('Бытовая техника', 'Бытовая техника'))), ('Досуг и хобби', (('Журналы, книги и издания', 'Журналы, книги и издания'), ('Животные', 'Животные'), ('Хобби', 'Хобби'), ('Знакомства', 'Знакомства'), ('Охота и рыбалка', 'Охота и рыбалка'), ('Часы и ювелирные изделия', 'Часы и ювелирные изделия'), ('Музыкальные инструменты', 'Музыкальные инструменты'), ('Спорт', 'Спорт'))), ('Работа', (('Бухгалтерский учет и аудит', 'Бухгалтерский учет и аудит'), ('IT, администрирование и поддержка', 'IT, администрирование и поддержка'), ('Реклама и маркетинг', 'Реклама и маркетинг'), ('Искусство и развлечение', 'Искусство и развлечение'), ('Автомобилестроение и механика', 'Автомобилестроение и механика'), ('Уход за детьми', 'Уход за детьми'), ('Обслуживание', 'Обслуживание'), ('Здравоохранение', 'Здравоохранение'), ('Гостиничный бизнес и туризм', 'Гостиничный бизнес и туризм'), ('Мода и красота', 'Мода и красота'), ('Графический дизайн и САПР', 'Графический дизайн и САПР'), ('Управление персоналом', 'Управление персоналом'), ('Установка и техническое обслуживание', 'Установка и техническое обслуживание'), ('Интернет и электронная коммерция', 'Интернет и электронная коммерция'), ('Правоохранительные органы, гос.управление', 'Правоохранительные органы, гос.управление'), ('Производство', 'Производство'), ('Менеджмент и управление', 'Менеджмент и управление'), ('Строительство', 'Строительство'), ('Горнодобывающая промышленность', 'Горнодобывающая промышленность'), ('Издательское дело, журналистика и СМИ', 'Издательское дело, журналистика и СМИ'), ('Закупки и мерчендайзинг', 'Закупки и мерчендайзинг'), ('Рестораны и общественное питание', 'Рестораны и общественное питание'), ('Розничная и оптовая торговля', 'Розничная и оптовая торговля'), ('Транспортные и складские услуги', 'Транспортные и складские услуги'), ('Ветеринарные услуги', 'Ветеринарные услуги'), ('Работа на дому', 'Работа на дому')))], db_index=True, max_length=70, null=True, verbose_name='Подрубрика'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='title',
            field=models.CharField(db_index=True, help_text='Это хелп', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='who',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Кто'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='whom',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Кого'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='your_age',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Возраст Ваш'),
        ),
    ]
