# Generated by Django 4.1.7 on 2023-03-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0009_rename_subrubrictransport_subrubric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrubric',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Подрубрика'),
        ),
    ]
