# Generated by Django 4.1.7 on 2023-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0010_adv_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
