# Generated by Django 4.1.7 on 2023-03-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0012_alter_subrubric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
    ]
