# Generated by Django 4.1.7 on 2023-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0013_adv_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='adv',
            name='car_mark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='adv',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='adv',
            name='car_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='adv',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='adv',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажей'),
        ),
        migrations.AddField(
            model_name='adv',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='adv',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='adv',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Комнат'),
        ),
        migrations.AddField(
            model_name='adv',
            name='square_land',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь земли'),
        ),
        migrations.AddField(
            model_name='adv',
            name='square_rooms',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь комнат'),
        ),
        migrations.AddField(
            model_name='adv',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='adv',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
