# Generated by Django 4.1.7 on 2023-03-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0017_region_alter_adv_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.AlterField(
            model_name='adv',
            name='car_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='all_adv.carmark', verbose_name='Марка'),
        ),
    ]
