# Generated by Django 4.1.7 on 2023-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0018_carmark_alter_adv_car_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='some_thing',
            field=models.CharField(choices=[('Купля-продажа', (('b', 'Куплю'), ('s', 'ПРодам'))), ('Обмен', (('с', 'Обменяю'),))], default='s', max_length=30),
        ),
    ]
