# Generated by Django 4.1.7 on 2023-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0019_adv_some_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='some_thing',
            field=models.CharField(choices=[('Купля-продажа', (('b', 'Куплю'), ('s', 'ПРодам'))), ('Обмен', (('с', 'Обменяю'),))], default='введите значение', max_length=30),
        ),
    ]
