# Generated by Django 4.1.7 on 2023-03-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_adv', '0021_remove_adv_some_thing_alter_adv_sub_rubric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='sub_rubric',
            new_name='subrubric',
        ),
    ]
